version: '3.3'

services:
  postgres:
    container_name: postgres_peuan_container
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - peuan
    # restart: unless-stopped

  pgadmin:
    container_name: pgadmin_peuan_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - peuan
    # restart: unless-stopped

  redis:
    container_name: redis_peuan_container
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - peuan

networks:
  peuan:

volumes:
  redis:
  postgres:
  pgadmin:
